version: '2'

services:

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
         soft: -1
         hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
      cluster.name: "ChicagoInfo"
    networks:
      - elk
  
  neo4j:
    image: neo4j:3.2.1          ## we use neo4j v3
    environment:
      - NEO4J_AUTH=neo4j/whatAstupid # configure the instance with custom username/password
      - NEO4J_HEAP_MEMORY=2048 # configure the heap memory
      - NEO4J_CACHE_MEMORY=1G # configure the cache memory
    ports:                    ## publish ports to have Web UI & BOLT
      - "7474:7474"
      - "7687:7687"
    volumes:                  ## adds folder with login/password
    - ./neo4j.3.2.1/data:/data
    - ./neo4j.3.2.1/logs:/logs
    - ./neo4j.3.2.1/plugins:/plugins
    - ./neo4j.3.2.1/config:/config
    networks:
      - elk
  # logstash:
  #   build: logstash/
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
